/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type AnsweringRuleInfo struct {

	// Canonical URI to the answering rule resource
	Uri string `json:"uri,omitempty"`

	// Internal identifier of an asnwering rule
	Id string `json:"id,omitempty"`

	// Type of an answering rule
	Type_ string `json:"type,omitempty"`

	// Name of an answering rule specified by user
	Name string `json:"name,omitempty"`

	// Specifies if an answering rule is active or inactive
	Enabled bool `json:"enabled,omitempty"`

	// Schedule when an answering rule should be applied
	Schedule ScheduleInfo `json:"schedule,omitempty"`

	// Answering rules are applied when calling to selected number(s)
	CalledNumbers []AnsweringRuleInfoCalleeInfo `json:"calledNumbers,omitempty"`

	// Answering rules are applied when calls are received from specified caller(s)
	Callers []AnsweringRuleInfoCallerInfo `json:"callers,omitempty"`

	// Specifies how incoming calls are forwarded
	CallHandlingAction string `json:"callHandlingAction,omitempty"`

	// Forwarding parameters. Returned if 'ForwardCalls' is specified in 'callHandlingAction'. These settings determine the forwarding numbers to which the call will be forwarded
	Forwarding ForwardingInfo `json:"forwarding,omitempty"`

	// Unconditional forwarding parameters. Returned if 'UnconditionalForwarding' is specified in 'callHandlingAction'
	UnconditionalForwarding UnconditionalForwardingInfo `json:"unconditionalForwarding,omitempty"`

	// Specifies whether to take a voicemail and who should do it
	Voicemail VoicemailInfo `json:"voicemail,omitempty"`

	// Predefined greetings applied for an answering rule
	Greetings []GreetingInfo `json:"greetings,omitempty"`
}
