/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type Body1 struct {

	// Active access or refresh token to be revoked
	Token string `json:"token,omitempty"`
}
