/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type Body13 struct {

	// Read status of a message to be changed. Multiple values are accepted
	ReadStatus string `json:"readStatus,omitempty"`
}
