/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type Body7 struct {

	// Multiple dial-in phone numbers to connect to audio conference service, relevant for user's brand. Each number is given with the country and location information, in order to let the user choose the less expensive way to connect to a conference. The first number in the list is the primary conference number, that is default and domestic
	PhoneNumbers []ConferencingRequestPhoneNumber `json:"phoneNumbers,omitempty"`

	// Determines if host user allows conference participants to join before the host
	AllowJoinBeforeHost bool `json:"allowJoinBeforeHost,omitempty"`
}
