/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type BusinessAddressInfo struct {

	// Name of a country
	Country string `json:"country,omitempty"`

	// Name of a state/province
	State string `json:"state,omitempty"`

	// Name of a city
	City string `json:"city,omitempty"`

	// Street address
	Street string `json:"street,omitempty"`

	// Zip code
	Zip string `json:"zip,omitempty"`
}
