/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type ContactInfo struct {

	// For User extension type only. Extension user first name
	FirstName string `json:"firstName,omitempty"`

	// For User extension type only. Extension user last name
	LastName string `json:"lastName,omitempty"`

	// Extension user company name
	Company string `json:"company,omitempty"`

	// Email of extension user
	Email string `json:"email,omitempty"`

	// Extension user contact phone number
	BusinessPhone string `json:"businessPhone,omitempty"`

	// Business address of extension user company
	BusinessAddress ContactAddressInfo `json:"businessAddress,omitempty"`
}
