/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type DepartmentInfo struct {

	// Internal identifier of a department extension
	Id string `json:"id,omitempty"`

	// Canonical URI of a department extension
	Uri string `json:"uri,omitempty"`

	// Number of a department extension
	ExtensionNumber string `json:"extensionNumber,omitempty"`
}
