/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type ExtensionInfoRequestContactInfo struct {

	// Contact information
	Contact ContactInfo `json:"contact,omitempty"`

	// Region data (timezone, home country, language)
	RegionalSettings ExtensionInfoRequestContactInfoRegionalSettings `json:"regionalSettings,omitempty"`

	// Specifies extension configuration wizard state (web service setup). The default value is 'NotStarted'
	SetupWizardState string `json:"setupWizardState,omitempty"`

	// Extension user department
	Department string `json:"department,omitempty"`
}
