/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type ExtensionInfoRequestContactInfoRegionalSettingsFormattingLocale struct {

	// Internal identifier of a formatting language
	Id string `json:"id,omitempty"`
}
