/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type ForwardingNumberInfo struct {

	// Internal identifier of a forwarding/call flip phone number
	Id string `json:"id,omitempty"`

	// Canonical URI of a forwarding/call flip phone number
	Uri string `json:"uri,omitempty"`

	// Forwarding/Call flip phone number
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// Forwarding/Call flip number title
	Label string `json:"label,omitempty"`

	// Type of option this phone number is used for. Multiple values are accepted
	Features string `json:"features,omitempty"`

	// Number assigned to the call flip phone number, corresponds to the shortcut dial number
	FlipNumber int32 `json:"flipNumber,omitempty"`
}
