/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

import (
	"time"
)

type IncomingCallNotification struct {

	// Event filter URI
	Event string `json:"event,omitempty"`

	// Universally unique identifier of a notification
	Uuid string `json:"uuid,omitempty"`

	// Internal identifier of a subscription
	SubscriptionId string `json:"subscriptionId,omitempty"`

	// The datetime of a call action in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
	Timestamp time.Time `json:"timestamp,omitempty"`

	// Internal identifier of an extension
	ExtensionId string `json:"extensionId,omitempty"`

	// Calling action, for example 'StartRing'
	Action string `json:"action,omitempty"`

	// Identifier of a call session
	SessionId string `json:"sessionId,omitempty"`

	// Identifier of a server
	ServerId string `json:"serverId,omitempty"`

	// Phone number of a caller
	From string `json:"from,omitempty"`

	// Caller name
	FromName string `json:"fromName,omitempty"`

	// Phone number of a callee
	To string `json:"to,omitempty"`

	// Callee name
	ToName string `json:"toName,omitempty"`

	// Unique identifier of a session
	Sid string `json:"sid,omitempty"`

	// SIP proxy registration name
	ToUrl string `json:"toUrl,omitempty"`

	// User data
	SrvLvl string `json:"srvLvl,omitempty"`

	// User data
	SrvLvlExt string `json:"srvLvlExt,omitempty"`

	// File containing recorded caller name
	RecUrl string `json:"recUrl,omitempty"`
}
