/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type InlineResponseDefault15 struct {

	// Canonical URI of a business-hours resource
	Uri string `json:"uri,omitempty"`

	// Schedule when an answering rule is applied
	Schedule BusinessHourScheduleInfo `json:"schedule,omitempty"`
}
