/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type InlineResponseDefault22 struct {

	// List of message records with synchronization information
	Records []MessageInfo `json:"records,omitempty"`

	// Sync type, token and time
	SyncInfo SyncInfo `json:"syncInfo,omitempty"`
}
