/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type LocationInfo struct {

	// Canonical URI of a location
	Uri string `json:"uri,omitempty"`

	// Area code of the location
	AreaCode string `json:"areaCode,omitempty"`

	// Official name of the city, belonging to the certain state
	City string `json:"city,omitempty"`

	// Area code of the location (3-digit usually), according to the NANP number format, that can be summarized as NPA-NXX-xxxx and covers Canada, the United States, parts of the Caribbean Sea, and some Atlantic and Pacific islands. See for details North American Numbering Plan
	Npa string `json:"npa,omitempty"`

	// Central office code of the location, according to the NANP number format, that can be summarized as NPA-NXX-xxxx and covers Canada, the United States, parts of the Caribbean Sea, and some Atlantic and Pacific islands. See for details North American Numbering Plan
	Nxx string `json:"nxx,omitempty"`

	// ID and URI of the state this location belongs to, see State Info
	State string `json:"state,omitempty"`
}
