/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type RegionalSettings struct {

	// Extension country information
	HomeCountry CountryInfo `json:"homeCountry,omitempty"`

	// Extension timezone information
	Timezone TimezoneInfo `json:"timezone,omitempty"`

	// User interface language data
	Language LanguageInfo `json:"language,omitempty"`

	// Information on language used for telephony greetings
	GreetingLanguage GreetingLanguageInfo `json:"greetingLanguage,omitempty"`

	// Formatting language preferences for numbers, dates and currencies
	FormattingLocale FormattingLocaleInfo `json:"formattingLocale,omitempty"`
}
