/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

import (
	"time"
)

type ReservePhoneNumberResponseReserveRecord struct {

	// Phone number in E.164 format without a '+'
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// Domestic format of a phone number
	FormattedNumber string `json:"formattedNumber,omitempty"`

	// The datetime up to which the number is reserved in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z. No value means that number is not reserved anymore
	ReservedTill time.Time `json:"reservedTill,omitempty"`

	// Internal identifier of phone number reservation; encoded data including reservation type (by brand, by account, by session), particular brand/account/session data, and reservation date and time
	ReservationId string `json:"reservationId,omitempty"`

	// Phone number status
	Status string `json:"status,omitempty"`

	// The error code in case of reservation/un-reservation failure
	Error_ string `json:"error,omitempty"`
}
