/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type RingOutRequestFrom struct {

	// Phone number in E.164 format
	PhoneNumber string `json:"phoneNumber,omitempty"`

	// Internal identifier of a forwarding number; returned in response in the id field. Can be specified instead of the phoneNumber attribute
	ForwardingNumberId string `json:"forwardingNumberId,omitempty"`
}
