/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type RingOutStatusInfo struct {

	// Status of a call
	CallStatus string `json:"callStatus,omitempty"`

	// Status of a calling party
	CallerStatus string `json:"callerStatus,omitempty"`

	// Status of a called party
	CalleeStatus string `json:"calleeStatus,omitempty"`
}
