/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type RuleInfo struct {

	// Forwarding number (or group) ordinal
	Index int32 `json:"index,omitempty"`

	// Number of rings for a forwarding number (or group)
	RingCount int32 `json:"ringCount,omitempty"`

	// Forwarding number (or group) data
	ForwardingNumbers []RuleInfoForwardingNumberInfo `json:"forwardingNumbers,omitempty"`
}
