/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type ScheduleInfo struct {

	// Weekly schedule
	WeeklyRanges WeeklyScheduleInfo `json:"weeklyRanges,omitempty"`

	// Specific data ranges
	Ranges RangesInfo `json:"ranges,omitempty"`

	// The user's schedule specified for business hours or after hours; it can also be set/retrieved calling the corresponding method
	Ref string `json:"ref,omitempty"`
}
