/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type ServicePlanInfo struct {

	// Internal identifier of a service plan
	Id string `json:"id,omitempty"`

	// Name of a service plan
	Name string `json:"name,omitempty"`

	// Edition of a service plan
	Edition string `json:"edition,omitempty"`
}
