/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type ServiceFeatureInfo struct {

	// Feature name, see all available values in Service Feature List
	FeatureName string `json:"featureName,omitempty"`

	// Feature status, shows feature availability for the extension
	Enabled bool `json:"enabled,omitempty"`
}
