/*
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type SipData struct {

	// Recipient data
	ToTag string `json:"toTag,omitempty"`

	// Sender data
	FromTag string `json:"fromTag,omitempty"`

	// Remote address URL
	RemoteUri string `json:"remoteUri,omitempty"`

	// Local address URL
	LocalUri string `json:"localUri,omitempty"`
}
