/* 
 * Ringcentral API
 *
 * RingCentral Connect Platform API
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package ringcentral

type StatusInfo struct {

	// A free-form user comment, describing the status change reason
	Comment string `json:"comment,omitempty"`

	// Type of suspension
	Reason string `json:"reason,omitempty"`
}
