/*
 * RingCentral Connect Platform API Explorer
 *
 * <p>This is a beta interactive API explorer for the RingCentral Connect Platform. To use this service, you will need to have an account with the proper credentials to generate an OAuth2 access token.</p><p><h2>Quick Start</h2></p><ol><li>1) Go to <b>Authentication > /oauth/token</b></li><li>2) Enter <b>app_key, app_secret, username, password</b> fields and then click \"Try it out!\"</li><li>3) Upon success, your access_token is loaded and you can access any form requiring authorization.</li></ol><h2>Links</h2><ul><li><a href=\"https://github.com/ringcentral\" target=\"_blank\">RingCentral SDKs on Github</a></li><li><a href=\"mailto:devsupport@ringcentral.com\">RingCentral Developer Support Email</a></li></ul>
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ringcentral

type UserCreationRequest struct {

	// Specification links
	Schemas []string `json:"schemas"`

	// User name
	Name *NameInfoRequest `json:"name"`

	// User mailbox
	UserName string `json:"userName"`

	// User email addresses
	Emails []EmailInfoRequest `json:"emails"`

	// User phone numbers
	PhoneNumbers []PhoneNumberInfoRequest `json:"phoneNumbers,omitempty"`

	// External identifier of a user
	ExternalId string `json:"externalId,omitempty"`

	// User addresses
	Addresses *AddressInfoRequest `json:"addresses,omitempty"`

	// Urn link
	Urnietfparamsscimschemasextensionenterprise20User *UrnInfoRequest `json:"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User,omitempty"`
}
