/*
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagedigital

import (
	"time"
)

type Event struct {
	CreatedAt  time.Time      `json:"created_at,omitempty"`
	ExtraInfos EventExtraInfo `json:"extra_infos,omitempty"`
	Id         string         `json:"id"`
	Name       string         `json:"name,omitempty"`
	UpdatedAt  time.Time      `json:"updated_at,omitempty"`
	UserId     string         `json:"user_id,omitempty"`
}
