/*
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagedigital

type Locale struct {
	Code      string `json:"code,omitempty"`
	Interface bool   `json:"interface,omitempty"`
	Name      string `json:"name,omitempty"`
}
