/*
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagedigital

import (
	"time"
)

type CustomField struct {
	AssociatedTypeName string    `json:"associated_type_name,omitempty"`
	CreatedAt          time.Time `json:"created_at,omitempty"`
	Id                 string    `json:"id"`
	Key                string    `json:"key,omitempty"`
	Label              string    `json:"label"`
	Multiple           bool      `json:"multiple,omitempty"`
	Position           int32     `json:"position,omitempty"`
	Type               string    `json:"type,omitempty"`
	UpdatedAt          time.Time `json:"updated_at,omitempty"`
}
