/*
 * RingCentral Engage Voice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagevoice

type ExtendedLeadData struct {
	Important  string `json:"important,omitempty"`
	Interested bool   `json:"interested,omitempty"`
}
