/*
 * RingCentral Engage Voice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagevoice

type Country struct {
	CountryCode string `json:"countryCode"`
	// Country code i ISO 3166-1 alpha-3 format
	CountryId    string `json:"countryId,omitempty"`
	CountryName  string `json:"countryName,omitempty"`
	MaxAniLength int32  `json:"maxAniLength,omitempty"`
	MaxUtcOffset int32  `json:"maxUtcOffset,omitempty"`
	MinAniLength int32  `json:"minAniLength,omitempty"`
	MinUtcOffset int32  `json:"minUtcOffset,omitempty"`
}
