/*
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagedigital

import (
	"time"
)

type ContentAttachment struct {
	ContentType string    `json:"content_type,omitempty"`
	CreatedAt   time.Time `json:"created_at,omitempty"`
	Embed       string    `json:"embed,omitempty"`
	Filename    string    `json:"filename,omitempty"`
	ForeignId   string    `json:"foreign_id,omitempty"`
	Id          string    `json:"id,omitempty"`
	Public      string    `json:"public?,omitempty"`
	Size        int32     `json:"size,omitempty"`
	UpdatedAt   time.Time `json:"updated_at,omitempty"`
	// You can download the attachments by using an API access token with the following URL: https://[your-domain].engagement.dimelo.com/attachments/[attachment_id]?access_token=[your_​ access_token]
	Url string `json:"url,omitempty"`
}
