/*
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagedigital

type Webhook struct {
	Active           bool               `json:"active,omitempty"`
	ApiAccessToken   WebhookAccessToken `json:"api_access_token,omitempty"`
	Id               string             `json:"id"`
	RegisteredEvents []string           `json:"registered_events,omitempty"`
	StagingUse       bool               `json:"staging_use,omitempty"`
	Url              string             `json:"url,omitempty"`
	VerifyToken      string             `json:"verify_token,omitempty"`
}
