/*
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagedigital

import (
	"time"
)

type Channel struct {
	CreatedAt          time.Time `json:"created_at,omitempty"`
	HardCapability     int32     `json:"hard_capability,omitempty"`
	Id                 string    `json:"id,omitempty"`
	Label              string    `json:"label,omitempty"`
	Name               string    `json:"name,omitempty"`
	SoftCapability     int32     `json:"soft_capability,omitempty"`
	SourceIds          []string  `json:"source_ids,omitempty"`
	TaskTimeoutSeconds int32     `json:"task_timeout_seconds,omitempty"`
	UpdatedAt          time.Time `json:"updated_at,omitempty"`
}
