/*
 * RingCentral Engage Voice API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package engagevoice

type Campaign struct {
	CampaignDesc string                   `json:"campaignDesc,omitempty"`
	CampaignId   int64                    `json:"campaignId,omitempty"`
	CampaignName string                   `json:"campaignName,omitempty"`
	DialGroup    Generic                  `json:"dialGroup,omitempty"`
	IsActive     int64                    `json:"isActive,omitempty"`
	Permissions  []map[string]interface{} `json:"permissions,omitempty"`
	Script       Generic                  `json:"script,omitempty"`
}
